/**:
    ros__parameters:
        common:
            lid_topic:  "/os1_points"
            imu_topic:  "/imu/data_raw"

            filter_size_surf: 0.25
            filter_size_map: 0.25

        kf:
            maximum_iter: 4
            epsi: 0.001
            NUM_MATCH_POINTS: 5
            plane_thr: 0.1

        preprocess:
            lidar_type: 3                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
            scan_line: 64
            blind: 2.0
            max_range: 40.0
            point_filter_num: 5

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            extrinsic_T: [ 1.77, -0.00, -0.05 ]
            extrinsic_R: [-1., 0., 0.,   0., -1., 0.,  0., 0., 1.]


        publish:
            path_en:  true
            scan_publish_en:  true       # false: close all the point cloud output
            dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
            runtime_pos_log: true
 

        pcd_save:
            pcd_save_en: 1  # 0 1(one pcd)  2()
            filter_size_savemap: 0.1
            savemap_dir: /home/qianliyue/D:/RepoMy/save/paper/mLT/
            
           
